CREATE DATABASE INVENTARIO
GO

USE INVENTARIO
GO

CREATE TABLE USERS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	USERNAME VARCHAR(50),
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(60),
	IMAGE VARCHAR(255),
	IS_ACTIVE BIT NOT NULL DEFAULT 1,
	IS_ADMIN BIT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME
)
GO

CREATE TABLE CATEGORY(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE VARCHAR(255),
	NAME VARCHAR(50),
	DESCRIPTION TEXT,
	CREATED_AT DATETIME
)
GO

CREATE TABLE PRODUCT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE VARCHAR(255),
	BARCODE VARCHAR(50),
	NAME VARCHAR(50),
	DESCRIPTION TEXT,
	INVENTARY_MIN INT DEFAULT 10,
	PRICE FLOAT,
	UNIT VARCHAR(255),
	PRESENTATION VARCHAR(255),
	USER_ID INT,
	CATEGORY_ID INT,
	CREATED_AT DATETIME,
	IS_ACTIVE BIT DEFAULT 1,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)
GO

CREATE TABLE PERSON(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE VARCHAR(255),
	NAME VARCHAR(255),
	LASTNAME VARCHAR(50),
	COMPANY VARCHAR(50),
	ADDRESS1 VARCHAR(50),
	ADDRESS2 VARCHAR(50),
	PHONE1 VARCHAR(50),
	PHONE2 VARCHAR(50),
	EMAIL1 VARCHAR(50),
	EMAIL2 VARCHAR(50),
	KIND INT,
	CREATED_AT DATETIME
)
GO

CREATE TABLE OPERATION_TYPE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(50)
)
GO

CREATE TABLE BOX(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CREATED_AT DATETIME
)
GO

CREATE TABLE SELL(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PERSON_ID INT FOREIGN KEY REFERENCES PERSON(ID),
	USER_ID INT FOREIGN KEY REFERENCES USERS(ID),
	OPERATION_TYPE_ID INT FOREIGN KEY REFERENCES OPERATION_TYPE(ID) DEFAULT 2,
	BOX_ID INT FOREIGN KEY REFERENCES BOX(ID),
	TOTAL DECIMAL,
	CASH DECIMAL,
	DISCOUNT DECIMAL,
	CREATED_AT DATETIME
)
GO

CREATE TABLE OPERATION(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(ID),
	Q FLOAT,
	OPERATION_TYPE_ID INT FOREIGN KEY REFERENCES OPERATION_TYPE(ID),
	SELL_ID INT FOREIGN KEY REFERENCES SELL(ID),
	CREATED_AT DATETIME
)
GO

CREATE TABLE CONFIGURATION(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SHORT VARCHAR(255) UNIQUE,
	NAME VARCHAR(255) UNIQUE,
	KIND INT,
	VAL VARCHAR(255)
)
GO

--CREACION DE DATA INICIAL DE LA DB (SEED)
--CREAMOS UN USUARIO
INSERT INTO USERS(NAME,LASTNAME,EMAIL,PASSWORD,IS_ACTIVE,IS_ADMIN,CREATED_AT) 
VALUES ('ADMINISTRADOR','','ADMIN','90B9AA7E25F80CF4F64E990B78A9FC5EBD6CECAD',1,1,GETDATE())

--INSERTAMSO EN TIPO DE OPERACION
INSERT INTO OPERATION_TYPE (NAME) VALUES ('ENTRADA')
INSERT INTO OPERATION_TYPE (NAME) VALUES ('SALIDA')

--INSERTAMOS DATOS DE CONFIGURACION
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('TITLE','TITULO DEL SISTEMA',2,'INVENTIO LITE');
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('USE_IMAGE_PRODUCT','UTILIZAR IMAGENES EN LOS PRODUCTOS',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_CLIENTS','ACTIVAR CLIENTES',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_PROVIDERS','ACTIVAR PROVEEDORES',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_CATEGORIES','ACTIVAR CATEGORIAS',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_REPORTS_WORD','ACTIVAR REPORTES EN WORD',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_REPORTS_EXCEL','ACTIVAR REPORTES EN EXCEL',1,0);
INSERT INTO CONFIGURATION(SHORT,NAME,KIND,VAL) VALUES('ACTIVE_REPORTS_PDF','ACTIVAR REPORTES EN PDF',1,0);
